emit metrics for pod killing and add tags for victims
kubewharf/katalyst-core pull request #49
Opened 2023-04-28 02:53 UTC by waynepeking348

#### What type of PR is this?
Enhancements

#### What this PR does / why we need it:
during evicting process, we miss tags for pod info, add this pr to make up this info

2023-04-28 08:47 UTC, luomingmeng approved these changes

2023-05-04 06:08 UTC, caohe requested changes

2023-05-04 06:08 UTC, caohe commented on pkg/agent/evictionmanager/podkiller/killer.go
> +			metrics.MetricTag{Key: "pod_nme", Val: pod.Name})
typo: pod_name

2023-05-04 06:09 UTC, caohe commented on pkg/agent/evictionmanager/podkiller/killer.go
> +		metrics.MetricTag{Key: "pod_nme", Val: pod.Name})
typo

2023-05-04 06:24 UTC, waynepeking348 commented on pkg/agent/evictionmanager/podkiller/killer.go
> +			metrics.MetricTag{Key: "pod_nme", Val: pod.Name})
fixed

2023-05-04 06:25 UTC, waynepeking348 commented on pkg/agent/evictionmanager/podkiller/killer.go
> +		metrics.MetricTag{Key: "pod_nme", Val: pod.Name})
fixed

2023-05-04 06:26 UTC, caohe approved these changes
LGTM

2023-05-04 06:26 UTC, csfldf approved these changes

2023-05-04 06:26 UTC, luomingmeng approved these changes

2023-05-04 06:36 UTC, merged